// Government Payment Services Configuration
// خدمات الدفع الحكومية القابلة للاختيار كخدمات

export interface GovernmentService {
  id: string;
  key: string;
  name: string;
  nameAr: string;
  country: string;
  type: 'government';
  supportsPaymentLinks: boolean;
  description: string;
  logo?: string;
  heroImage?: string;
}

// تعريف خدمات الدفع الحكومية والمحلية
export const governmentServices: GovernmentService[] = [
  // السعودية - سداد
  {
    id: 'sadad-passport',
    key: 'sadad-passport',
    name: 'SADAD Passport',
    nameAr: 'سداد جواز السفر',
    country: 'SA',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'تجديد وإصدار جوازات السفر عبر سداد',
    logo: '/gov-sadad-official.png',
    heroImage: '/gov-sadad-official.png',
  },
  {
    id: 'sadad-traffic-violations',
    key: 'sadad-traffic-violations',
    name: 'SADAD Traffic Violations',
    nameAr: 'سداد المخالفات المرورية',
    country: 'SA',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'دفع مخالفات المرور عبر سداد',
    logo: '/gov-sadad-official.png',
    heroImage: '/gov-sadad-official.png',
  },
  {
    id: 'sadad-driving-license',
    key: 'sadad-driving-license',
    name: 'SADAD Driving License',
    nameAr: 'سداد رخصة القيادة',
    country: 'SA',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'إصدار وتجديد رخص القيادة عبر سداد',
    logo: '/gov-sadad-official.png',
    heroImage: '/gov-sadad-official.png',
  },
  {
    id: 'sadad-municipal',
    key: 'sadad-municipal',
    name: 'SADAD Municipal Services',
    nameAr: 'سداد الخدمات البلدية',
    country: 'SA',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'دفع رسوم الخدمات البلدية عبر سداد',
    logo: '/gov-sadad-official.png',
    heroImage: '/gov-sadad-official.png',
  },
  {
    id: 'sadad-contracts',
    key: 'sadad-contracts',
    name: 'SADAD Contracts',
    nameAr: 'سداد العقود',
    country: 'SA',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'دفع رسوم توثيق العقود عبر سداد',
    logo: '/gov-sadad-official.png',
    heroImage: '/gov-sadad-official.png',
  },
  {
    id: 'sadad-id-card',
    key: 'sadad-id-card',
    name: 'SADAD ID Card',
    nameAr: 'سداد بطاقة الأحوال',
    country: 'SA',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'إصدار وتجديد بطاقة الأحوال المدنية',
    logo: '/gov-sadad-official.png',
    heroImage: '/gov-sadad-official.png',
  },
  {
    id: 'sadad-education',
    key: 'sadad-education',
    name: 'SADAD Education',
    nameAr: 'سداد الخدمات التعليمية',
    country: 'SA',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'دفع الرسوم الدراسية والخدمات التعليمية',
    logo: '/gov-sadad-official.png',
    heroImage: '/gov-sadad-official.png',
  },
  {
    id: 'sadad-health',
    key: 'sadad-health',
    name: 'SADAD Health',
    nameAr: 'سداد الخدمات الصحية',
    country: 'SA',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'دفع رسوم المستشفيات والخدمات الصحية',
    logo: '/gov-sadad-official.png',
    heroImage: '/gov-sadad-official.png',
  },
  {
    id: 'sadad-work-permit',
    key: 'sadad-work-permit',
    name: 'SADAD Work Permit',
    nameAr: 'سداد تصاريح العمل',
    country: 'SA',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'دفع رسوم تصاريح العمل والإقامة',
    logo: '/gov-sadad-official.png',
    heroImage: '/gov-sadad-official.png',
  },
  {
    id: 'sadad-insurance',
    key: 'sadad-insurance',
    name: 'SADAD Insurance',
    nameAr: 'سداد التأمين',
    country: 'SA',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'دفع أقساط التأمين الطبي والسيارات',
    logo: '/gov-sadad-official.png',
    heroImage: '/gov-sadad-official.png',
  },
  {
    id: 'sadad-vehicle-registration',
    key: 'sadad-vehicle-registration',
    name: 'SADAD Vehicle Registration',
    nameAr: 'سداد استمارة المركبة',
    country: 'SA',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'تجديد استمارة المركبة عبر سداد',
    logo: '/gov-sadad-official.png',
    heroImage: '/gov-sadad-official.png',
  },
  {
    id: 'sadad-customs',
    key: 'sadad-customs',
    name: 'SADAD Customs',
    nameAr: 'سداد الجمارك',
    country: 'SA',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'دفع الرسوم الجمركية عبر سداد',
    logo: '/gov-sadad-official.png',
    heroImage: '/gov-sadad-official.png',
  },
  {
    id: 'sadad-utilities',
    key: 'sadad-utilities',
    name: 'SADAD Utilities',
    nameAr: 'سداد فواتير الخدمات',
    country: 'SA',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'دفع فواتير الكهرباء والماء والاتصالات',
    logo: '/gov-sadad-official.png',
    heroImage: '/gov-sadad-official.png',
  },
  {
    id: 'sadad-zakat',
    key: 'sadad-zakat',
    name: 'SADAD Zakat',
    nameAr: 'سداد الزكاة والدخل',
    country: 'SA',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'دفع مستحقات الزكاة والدخل والضرائب',
    logo: '/gov-sadad-official.png',
    heroImage: '/gov-sadad-official.png',
  },
  {
    id: 'sadad-housing',
    key: 'sadad-housing',
    name: 'SADAD Housing',
    nameAr: 'سداد الإسكان',
    country: 'SA',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'دفع رسوم الإسكان والخدمات العقارية',
    logo: '/gov-sadad-official.png',
    heroImage: '/gov-sadad-official.png',
  },
  {
    id: 'sadad-telecom',
    key: 'sadad-telecom',
    name: 'SADAD Telecom',
    nameAr: 'سداد الاتصالات',
    country: 'SA',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'دفع فواتير الاتصالات والإنترنت',
    logo: '/gov-sadad-official.png',
    heroImage: '/gov-sadad-official.png',
  },
  {
    id: 'sadad-iqama',
    key: 'sadad-iqama',
    name: 'SADAD Iqama',
    nameAr: 'سداد الإقامة',
    country: 'SA',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'تجديد الإقامة ورسوم الكفالة',
    logo: '/gov-sadad-official.png',
    heroImage: '/gov-sadad-official.png',
  },
  {
    id: 'sadad-commercial',
    key: 'sadad-commercial',
    name: 'SADAD Commercial',
    nameAr: 'سداد السجل التجاري',
    country: 'SA',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'رسوم السجل التجاري والتراخيص',
    logo: '/gov-sadad-official.png',
    heroImage: '/gov-sadad-official.png',
  },
  {
    id: 'sadad-justice',
    key: 'sadad-justice',
    name: 'SADAD Justice',
    nameAr: 'سداد وزارة العدل',
    country: 'SA',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'رسوم الصكوك والوثائق العدلية',
    logo: '/gov-sadad-official.png',
    heroImage: '/gov-sadad-official.png',
  },
  {
    id: 'sadad-courts',
    key: 'sadad-courts',
    name: 'SADAD Courts',
    nameAr: 'سداد المحاكم',
    country: 'SA',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'رسوم المحاكم والقضايا',
    logo: '/gov-sadad-official.png',
    heroImage: '/gov-sadad-official.png',
  },
  {
    id: 'sadad',
    key: 'sadad',
    name: 'SADAD General',
    nameAr: 'سداد - عام',
    country: 'SA',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'نظام المدفوعات الوطني السعودي للخدمات الحكومية',
    logo: '/gov-sadad-official.png',
    heroImage: '/gov-sadad-official.png',
  },

  // البحرين - بنفت
  {
    id: 'benefit-passport',
    key: 'benefit-passport',
    name: 'BENEFIT Passport',
    nameAr: 'بنفت جواز السفر',
    country: 'BH',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'تجديد وإصدار جوازات السفر عبر بنفت',
    logo: '/gov-benefit-logo.png',
    heroImage: '/gov-benefit-logo.png',
  },
  {
    id: 'benefit-traffic',
    key: 'benefit-traffic',
    name: 'BENEFIT Traffic',
    nameAr: 'بنفت المخالفات المرورية',
    country: 'BH',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'دفع مخالفات المرور عبر بنفت',
    logo: '/gov-benefit-logo.png',
    heroImage: '/gov-benefit-logo.png',
  },
  {
    id: 'benefit-cpr',
    key: 'benefit-cpr',
    name: 'BENEFIT CPR',
    nameAr: 'بنفت بطاقة CPR',
    country: 'BH',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'إصدار وتجديد البطاقة الشخصية',
    logo: '/gov-benefit-logo.png',
    heroImage: '/gov-benefit-logo.png',
  },
  {
    id: 'benefit-municipal',
    key: 'benefit-municipal',
    name: 'BENEFIT Municipal',
    nameAr: 'بنفت الخدمات البلدية',
    country: 'BH',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'دفع رسوم الخدمات البلدية',
    logo: '/gov-benefit-logo.png',
    heroImage: '/gov-benefit-logo.png',
  },
  {
    id: 'benefit-utilities',
    key: 'benefit-utilities',
    name: 'BENEFIT Utilities',
    nameAr: 'بنفت فواتير الخدمات',
    country: 'BH',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'فواتير الكهرباء والماء',
    logo: '/gov-benefit-logo.png',
    heroImage: '/gov-benefit-logo.png',
  },
  {
    id: 'benefit-telecom',
    key: 'benefit-telecom',
    name: 'BENEFIT Telecom',
    nameAr: 'بنفت الاتصالات',
    country: 'BH',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'فواتير الاتصالات والإنترنت',
    logo: '/gov-benefit-logo.png',
    heroImage: '/gov-benefit-logo.png',
  },
  {
    id: 'benefit-business',
    key: 'benefit-business',
    name: 'BENEFIT Business',
    nameAr: 'بنفت السجل التجاري',
    country: 'BH',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'رسوم السجل التجاري',
    logo: '/gov-benefit-logo.png',
    heroImage: '/gov-benefit-logo.png',
  },
  {
    id: 'benefit-health',
    key: 'benefit-health',
    name: 'BENEFIT Health',
    nameAr: 'بنفت الخدمات الصحية',
    country: 'BH',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'رسوم المستشفيات والعلاج',
    logo: '/gov-benefit-logo.png',
    heroImage: '/gov-benefit-logo.png',
  },
  {
    id: 'benefit-education',
    key: 'benefit-education',
    name: 'BENEFIT Education',
    nameAr: 'بنفت الخدمات التعليمية',
    country: 'BH',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'الرسوم الدراسية والتعليمية',
    logo: '/gov-benefit-logo.png',
    heroImage: '/gov-benefit-logo.png',
  },
  {
    id: 'benefit-visa',
    key: 'benefit-visa',
    name: 'BENEFIT Visa',
    nameAr: 'بنفت خدمات الإقامة',
    country: 'BH',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'رسوم الإقامة والتأشيرات',
    logo: '/gov-benefit-logo.png',
    heroImage: '/gov-benefit-logo.png',
  },
  {
    id: 'benefit',
    key: 'benefit',
    name: 'BENEFIT General',
    nameAr: 'بنفت - عام',
    country: 'BH',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'الشبكة الإلكترونية البحرينية للمعاملات المالية',
    logo: '/gov-benefit-logo.png',
    heroImage: '/gov-benefit-logo.png',
  },

  // الكويت - كي نت
  {
    id: 'knet-passport',
    key: 'knet-passport',
    name: 'KNET Passport',
    nameAr: 'كي نت جواز السفر',
    country: 'KW',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'تجديد وإصدار جوازات السفر عبر كي نت',
    logo: '/gov-knet-logo.png',
    heroImage: '/gov-knet-logo.png',
  },
  {
    id: 'knet-paci',
    key: 'knet-paci',
    name: 'KNET PACI',
    nameAr: 'كي نت البطاقة المدنية',
    country: 'KW',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'رسوم البطاقة المدنية عبر كي نت',
    logo: '/gov-knet-logo.png',
    heroImage: '/gov-knet-logo.png',
  },
  {
    id: 'knet-traffic',
    key: 'knet-traffic',
    name: 'KNET Traffic',
    nameAr: 'كي نت المخالفات المرورية',
    country: 'KW',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'دفع مخالفات المرور عبر كي نت',
    logo: '/gov-knet-logo.png',
    heroImage: '/gov-knet-logo.png',
  },
  {
    id: 'knet-municipal',
    key: 'knet-municipal',
    name: 'KNET Municipal',
    nameAr: 'كي نت الخدمات البلدية',
    country: 'KW',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'دفع رسوم البلدية عبر كي نت',
    logo: '/gov-knet-logo.png',
    heroImage: '/gov-knet-logo.png',
  },
  {
    id: 'knet-utilities',
    key: 'knet-utilities',
    name: 'KNET Utilities',
    nameAr: 'كي نت فواتير الخدمات',
    country: 'KW',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'فواتير الكهرباء والماء والغاز',
    logo: '/gov-knet-logo.png',
    heroImage: '/gov-knet-logo.png',
  },
  {
    id: 'knet-telecom',
    key: 'knet-telecom',
    name: 'KNET Telecom',
    nameAr: 'كي نت الاتصالات',
    country: 'KW',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'فواتير الاتصالات والإنترنت',
    logo: '/gov-knet-logo.png',
    heroImage: '/gov-knet-logo.png',
  },
  {
    id: 'knet-business',
    key: 'knet-business',
    name: 'KNET Business',
    nameAr: 'كي نت الترخيص التجاري',
    country: 'KW',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'رسوم التراخيص التجارية',
    logo: '/gov-knet-logo.png',
    heroImage: '/gov-knet-logo.png',
  },
  {
    id: 'knet-health',
    key: 'knet-health',
    name: 'KNET Health',
    nameAr: 'كي نت الخدمات الصحية',
    country: 'KW',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'رسوم المستشفيات والعلاج',
    logo: '/gov-knet-logo.png',
    heroImage: '/gov-knet-logo.png',
  },
  {
    id: 'knet-education',
    key: 'knet-education',
    name: 'KNET Education',
    nameAr: 'كي نت الخدمات التعليمية',
    country: 'KW',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'الرسوم الدراسية والتعليمية',
    logo: '/gov-knet-logo.png',
    heroImage: '/gov-knet-logo.png',
  },
  {
    id: 'knet',
    key: 'knet',
    name: 'KNET General',
    nameAr: 'كي نت - عام',
    country: 'KW',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'شبكة الكويت الوطنية للمدفوعات الإلكترونية',
    logo: '/gov-knet-logo.png',
    heroImage: '/gov-knet-logo.png',
  },

  // عُمان - عُمان نت
  {
    id: 'omannet-passport',
    key: 'omannet-passport',
    name: 'OmanNet Passport',
    nameAr: 'عُمان نت جواز السفر',
    country: 'OM',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'تجديد وإصدار جوازات السفر',
    logo: '/gov-maal-logo.jpg',
    heroImage: '/gov-maal-logo.jpg',
  },
  {
    id: 'omannet-id',
    key: 'omannet-id',
    name: 'OmanNet ID',
    nameAr: 'عُمان نت بطاقة الهوية',
    country: 'OM',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'إصدار وتجديد بطاقة الهوية',
    logo: '/gov-maal-logo.jpg',
    heroImage: '/gov-maal-logo.jpg',
  },
  {
    id: 'omannet-traffic',
    key: 'omannet-traffic',
    name: 'OmanNet Traffic',
    nameAr: 'عُمان نت المخالفات المرورية',
    country: 'OM',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'دفع مخالفات المرور',
    logo: '/gov-maal-logo.jpg',
    heroImage: '/gov-maal-logo.jpg',
  },
  {
    id: 'omannet-municipal',
    key: 'omannet-municipal',
    name: 'OmanNet Municipal',
    nameAr: 'عُمان نت الخدمات البلدية',
    country: 'OM',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'دفع رسوم الخدمات البلدية',
    logo: '/gov-maal-logo.jpg',
    heroImage: '/gov-maal-logo.jpg',
  },
  {
    id: 'omannet-utilities',
    key: 'omannet-utilities',
    name: 'OmanNet Utilities',
    nameAr: 'عُمان نت فواتير الخدمات',
    country: 'OM',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'فواتير الكهرباء والماء',
    logo: '/gov-maal-logo.jpg',
    heroImage: '/gov-maal-logo.jpg',
  },
  {
    id: 'omannet-telecom',
    key: 'omannet-telecom',
    name: 'OmanNet Telecom',
    nameAr: 'عُمان نت الاتصالات',
    country: 'OM',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'فواتير الاتصالات والإنترنت',
    logo: '/gov-maal-logo.jpg',
    heroImage: '/gov-maal-logo.jpg',
  },
  {
    id: 'omannet-business',
    key: 'omannet-business',
    name: 'OmanNet Business',
    nameAr: 'عُمان نت السجل التجاري',
    country: 'OM',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'رسوم السجل التجاري',
    logo: '/gov-maal-logo.jpg',
    heroImage: '/gov-maal-logo.jpg',
  },
  {
    id: 'omannet-health',
    key: 'omannet-health',
    name: 'OmanNet Health',
    nameAr: 'عُمان نت الخدمات الصحية',
    country: 'OM',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'رسوم المستشفيات والعلاج',
    logo: '/gov-maal-logo.jpg',
    heroImage: '/gov-maal-logo.jpg',
  },
  {
    id: 'omannet-visa',
    key: 'omannet-visa',
    name: 'OmanNet Visa',
    nameAr: 'عُمان نت خدمات الإقامة',
    country: 'OM',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'رسوم الإقامة والتأشيرات',
    logo: '/gov-maal-logo.jpg',
    heroImage: '/gov-maal-logo.jpg',
  },
  {
    id: 'omannet',
    key: 'omannet',
    name: 'OmanNet General',
    nameAr: 'عُمان نت - عام',
    country: 'OM',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'شبكة عُمان للمدفوعات الإلكترونية - بطاقة مال',
    logo: '/gov-maal-logo.jpg',
    heroImage: '/gov-maal-logo.jpg',
  },

  // الإمارات - جيوان
  {
    id: 'jaywan-passport',
    key: 'jaywan-passport',
    name: 'Jaywan Passport',
    nameAr: 'جيوان جواز السفر',
    country: 'AE',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'تجديد وإصدار جوازات السفر',
    logo: '/gov-uae-logo.jpg',
    heroImage: '/gov-uae-logo.jpg',
  },
  {
    id: 'jaywan-emirates-id',
    key: 'jaywan-emirates-id',
    name: 'Jaywan Emirates ID',
    nameAr: 'جيوان الهوية الإماراتية',
    country: 'AE',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'إصدار وتجديد الهوية الإماراتية',
    logo: '/gov-uae-logo.jpg',
    heroImage: '/gov-uae-logo.jpg',
  },
  {
    id: 'jaywan-traffic',
    key: 'jaywan-traffic',
    name: 'Jaywan Traffic',
    nameAr: 'جيوان المخالفات المرورية',
    country: 'AE',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'دفع مخالفات المرور',
    logo: '/gov-uae-logo.jpg',
    heroImage: '/gov-uae-logo.jpg',
  },
  {
    id: 'jaywan-municipal',
    key: 'jaywan-municipal',
    name: 'Jaywan Municipal',
    nameAr: 'جيوان الخدمات البلدية',
    country: 'AE',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'دفع رسوم الخدمات البلدية',
    logo: '/gov-uae-logo.jpg',
    heroImage: '/gov-uae-logo.jpg',
  },
  {
    id: 'jaywan-visa',
    key: 'jaywan-visa',
    name: 'Jaywan Visa',
    nameAr: 'جيوان خدمات الإقامة',
    country: 'AE',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'رسوم الإقامة والتأشيرات',
    logo: '/gov-uae-logo.jpg',
    heroImage: '/gov-uae-logo.jpg',
  },
  {
    id: 'jaywan-utilities',
    key: 'jaywan-utilities',
    name: 'Jaywan Utilities',
    nameAr: 'جيوان فواتير الخدمات',
    country: 'AE',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'فواتير الكهرباء والماء والغاز',
    logo: '/gov-uae-logo.jpg',
    heroImage: '/gov-uae-logo.jpg',
  },
  {
    id: 'jaywan-telecom',
    key: 'jaywan-telecom',
    name: 'Jaywan Telecom',
    nameAr: 'جيوان الاتصالات',
    country: 'AE',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'فواتير الاتصالات والإنترنت',
    logo: '/gov-uae-logo.jpg',
    heroImage: '/gov-uae-logo.jpg',
  },
  {
    id: 'jaywan-housing',
    key: 'jaywan-housing',
    name: 'Jaywan Housing',
    nameAr: 'جيوان الإسكان',
    country: 'AE',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'رسوم الإسكان والعقارات',
    logo: '/gov-uae-logo.jpg',
    heroImage: '/gov-uae-logo.jpg',
  },
  {
    id: 'jaywan-business',
    key: 'jaywan-business',
    name: 'Jaywan Business',
    nameAr: 'جيوان الرخصة التجارية',
    country: 'AE',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'رسوم الرخص التجارية والأعمال',
    logo: '/gov-uae-logo.jpg',
    heroImage: '/gov-uae-logo.jpg',
  },
  {
    id: 'jaywan-health',
    key: 'jaywan-health',
    name: 'Jaywan Health',
    nameAr: 'جيوان الخدمات الصحية',
    country: 'AE',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'رسوم المستشفيات والعلاج',
    logo: '/gov-uae-logo.jpg',
    heroImage: '/gov-uae-logo.jpg',
  },
  {
    id: 'jaywan-education',
    key: 'jaywan-education',
    name: 'Jaywan Education',
    nameAr: 'جيوان الخدمات التعليمية',
    country: 'AE',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'الرسوم الدراسية والتعليمية',
    logo: '/gov-uae-logo.jpg',
    heroImage: '/gov-uae-logo.jpg',
  },
  {
    id: 'jaywan-salik',
    key: 'jaywan-salik',
    name: 'Jaywan Salik',
    nameAr: 'جيوان سالك',
    country: 'AE',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'رسوم سالك وبوابات المرور',
    logo: '/gov-uae-logo.jpg',
    heroImage: '/gov-uae-logo.jpg',
  },
  {
    id: 'jaywan',
    key: 'jaywan',
    name: 'Jaywan General',
    nameAr: 'جيوان - عام',
    country: 'AE',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'نظام البطاقة الوطنية الإماراتي للدفع الإلكتروني',
    logo: '/gov-uae-logo.jpg',
    heroImage: '/gov-uae-logo.jpg',
  },

  // قطر - بوابة الدفع الحكومي
  {
    id: 'qatar-passport',
    key: 'qatar-passport',
    name: 'Qatar Passport',
    nameAr: 'بوابة الدفع - جواز السفر',
    country: 'QA',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'تجديد وإصدار جوازات السفر',
    logo: '/gov-qatar-logo.png',
    heroImage: '/gov-qatar-logo.png',
  },
  {
    id: 'qatar-id',
    key: 'qatar-id',
    name: 'Qatar ID',
    nameAr: 'بوابة الدفع - بطاقة الهوية',
    country: 'QA',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'إصدار وتجديد بطاقة الهوية',
    logo: '/gov-qatar-logo.png',
    heroImage: '/gov-qatar-logo.png',
  },
  {
    id: 'qatar-traffic',
    key: 'qatar-traffic',
    name: 'Qatar Traffic',
    nameAr: 'بوابة الدفع - المخالفات المرورية',
    country: 'QA',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'دفع مخالفات المرور',
    logo: '/gov-qatar-logo.png',
    heroImage: '/gov-qatar-logo.png',
  },
  {
    id: 'qatar-municipal',
    key: 'qatar-municipal',
    name: 'Qatar Municipal',
    nameAr: 'بوابة الدفع - الخدمات البلدية',
    country: 'QA',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'دفع رسوم الخدمات البلدية',
    logo: '/gov-qatar-logo.png',
    heroImage: '/gov-qatar-logo.png',
  },
  {
    id: 'qatar-utilities',
    key: 'qatar-utilities',
    name: 'Qatar Utilities',
    nameAr: 'بوابة الدفع - فواتير الخدمات',
    country: 'QA',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'فواتير الكهرباء والماء',
    logo: '/gov-qatar-logo.png',
    heroImage: '/gov-qatar-logo.png',
  },
  {
    id: 'qatar-telecom',
    key: 'qatar-telecom',
    name: 'Qatar Telecom',
    nameAr: 'بوابة الدفع - الاتصالات',
    country: 'QA',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'فواتير الاتصالات والإنترنت',
    logo: '/gov-qatar-logo.png',
    heroImage: '/gov-qatar-logo.png',
  },
  {
    id: 'qatar-business',
    key: 'qatar-business',
    name: 'Qatar Business',
    nameAr: 'بوابة الدفع - السجل التجاري',
    country: 'QA',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'رسوم السجل التجاري',
    logo: '/gov-qatar-logo.png',
    heroImage: '/gov-qatar-logo.png',
  },
  {
    id: 'qatar-health',
    key: 'qatar-health',
    name: 'Qatar Health',
    nameAr: 'بوابة الدفع - الخدمات الصحية',
    country: 'QA',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'رسوم المستشفيات والعلاج',
    logo: '/gov-qatar-logo.png',
    heroImage: '/gov-qatar-logo.png',
  },
  {
    id: 'qatar-education',
    key: 'qatar-education',
    name: 'Qatar Education',
    nameAr: 'بوابة الدفع - الخدمات التعليمية',
    country: 'QA',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'الرسوم الدراسية والتعليمية',
    logo: '/gov-qatar-logo.png',
    heroImage: '/gov-qatar-logo.png',
  },
  {
    id: 'qatar-visa',
    key: 'qatar-visa',
    name: 'Qatar Visa',
    nameAr: 'بوابة الدفع - خدمات الإقامة',
    country: 'QA',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'رسوم الإقامة والتأشيرات',
    logo: '/gov-qatar-logo.png',
    heroImage: '/gov-qatar-logo.png',
  },
  {
    id: 'qatar-gov',
    key: 'qatar-gov',
    name: 'Qatar Gov Payment',
    nameAr: 'بوابة الدفع الحكومي القطرية - عام',
    country: 'QA',
    type: 'government',
    supportsPaymentLinks: true,
    description: 'نظام الدفع الإلكتروني للخدمات الحكومية القطرية',
    logo: '/gov-qatar-logo.png',
    heroImage: '/gov-qatar-logo.png',
  },
];

/**
 * Get government services by country code
 * الحصول على خدمات الدفع الحكومية حسب رمز الدولة
 */
export const getGovernmentServicesByCountry = (countryCode: string): GovernmentService[] => {
  return governmentServices.filter(service => service.country === countryCode.toUpperCase());
};

/**
 * Get government service by key
 * الحصول على خدمة دفع حكومية بواسطة المفتاح
 */
export const getGovernmentServiceByKey = (key: string): GovernmentService | undefined => {
  return governmentServices.find(service => service.key === key);
};

/**
 * Check if a service key is a government service
 * التحقق من أن المفتاح يشير إلى خدمة حكومية
 */
export const isGovernmentService = (key: string): boolean => {
  return governmentServices.some(service => service.key === key);
};

/**
 * Get all government services
 * الحصول على جميع خدمات الدفع الحكومية
 */
export const getAllGovernmentServices = (): GovernmentService[] => {
  return governmentServices;
};

/**
 * Get government service meta data by country code
 * الحصول على بيانات الخدمة الحكومية حسب رمز الدولة
 */
export const getGovernmentServiceMeta = (countryCode: string): { title: string; description: string; image: string; service: GovernmentService | undefined } => {
  const service = governmentServices.find(s => s.country === countryCode.toUpperCase());
  
  const metaData: Record<string, { title: string; description: string; image: string }> = {
    SA: {
      title: "سداد - جواز السفر، المخالفات المرورية، رخصة القيادة والمزيد 🇸🇦",
      description: "نظام سداد السعودي SADAD | دفع رسوم جواز السفر، المخالفات المرورية، رخصة القيادة، الخدمات البلدية، العقود، بطاقة الأحوال، الخدمات التعليمية والصحية، تصاريح العمل، التأمين، استمارة المركبة، الجمارك وفواتير الخدمات | معتمد من البنك المركزي السعودي 🏛️",
      image: "/og-sadad.jpg"
    },
    BH: {
      title: "بنفت - جواز السفر، المخالفات والخدمات الحكومية 🇧🇭",
      description: "شبكة بنفت البحرينية BENEFIT | دفع رسوم جواز السفر، المخالفات المرورية، بطاقة CPR، الخدمات البلدية وجميع الخدمات الحكومية | شبكة المدفوعات الوطنية الموثوقة 💳",
      image: "/og-benefit.jpg"
    },
    KW: {
      title: "كي نت - جواز السفر، البطاقة المدنية والخدمات الحكومية 🇰🇼",
      description: "شبكة كي نت الكويتية KNET | دفع رسوم جواز السفر، البطاقة المدنية، المخالفات المرورية، الخدمات البلدية وجميع الخدمات الحكومية | نظام الدفع الإلكتروني الرائد في الكويت ✅",
      image: "/og-knet.jpg"
    },
    AE: {
      title: "الدرهم الإلكتروني - جواز السفر، الهوية الإماراتية والخدمات الحكومية 🇦🇪",
      description: "نظام الدرهم الإلكتروني الإماراتي eDirham | دفع رسوم جواز السفر، الهوية الإماراتية، المخالفات المرورية، الخدمات البلدية، خدمات الإقامة، سالك وجميع الخدمات الحكومية | نظام الدفع الإلكتروني الوطني المعتمد 🏛️",
      image: "/og-edirham.jpg"
    },
    OM: {
      title: "مال - جواز السفر، بطاقة الهوية والخدمات الحكومية 🇴🇲",
      description: "بطاقة مال العُمانية Maal Card | دفع رسوم جواز السفر، بطاقة الهوية، المخالفات المرورية، الخدمات البلدية وجميع الخدمات الحكومية | شبكة الدفع الإلكتروني الوطنية 💳",
      image: "/og-maal.jpg"
    },
    QA: {
      title: "بوابة الدفع القطرية - جواز السفر، بطاقة الهوية والخدمات الحكومية 🇶🇦",
      description: "بوابة الدفع الحكومي القطرية | دفع رسوم جواز السفر، بطاقة الهوية، المخالفات المرورية، الخدمات البلدية وجميع الخدمات الحكومية في قطر | نظام الدفع الإلكتروني الرسمي 🏛️",
      image: "/og-qatar-gov.jpg"
    }
  };
  
  const meta = metaData[countryCode.toUpperCase()] || metaData.SA;
  
  return {
    ...meta,
    service
  };
};
